version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sbms
    ports:
      - "3306:3306"
    networks:
      - springboot-db-net

  app:
    build: .
    image: springboot-mysql-app
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net

networks:
  springboot-db-net: